### ISSUE TITLE
gbx3: warning: 4 allocation(s) non freed.

### ISSUE THREAD

**Issue by shirishag75** [eloaders/I-Nex#7]
Hi all, 
Got the above while closing the application :-

    $ i-nex
    [01/20/2015 10:55:54.918] [INFO] [Finfosys.Form_Open.49] Starting log
    [01/20/2015 10:55:54.937] [INFO] [Finfosys.Form_Open.70] TabStrip1.Orientation Top
    [01/20/2015 10:55:54.951] [INFO] [Finfosys.Form_Open.78] Check whereis inex-cpuid and get JSON Data
    [01/20/2015 10:55:55.86] [INFO] [Finfosys.Form_Open.80] Decode JSON Data
    [01/20/2015 10:55:55.877] [INFO] [Finfosys.Form_Open.82] Add Values CPUID
    [01/20/2015 10:55:55.878] [INFO] [Finfosys.Form_Open.113] Create Labels ToolButtons TextLabels in ScrollView1
    [01/20/2015 10:55:55.95] [INFO] [Finfosys.Form_Open.205] Check available procesors
    [01/20/2015 10:55:55.959] [INFO] [Finfosys.Form_Open.225] /home/shirish/.i-nex/i-nex.conf
    [01/20/2015 10:55:55.959] [INFO] [Finfosys.Form_Open.226] /home/shirish/.i-nex
    [01/20/2015 10:55:55.962] [INFO] [Finfosys.Form_Open.229] Call to MInit for copy nedded files to I-Nex config dir in User.Home
    [01/20/2015 10:55:55.962] [INFO] [MInit._inits.26] i-nex in home folder is exist
    [01/20/2015 10:55:55.962] [INFO] [MInit._inits.27] Try to remove files
    [01/20/2015 10:55:55.962] [INFO] [MInit._inits.36] Copy nedded files
    [01/20/2015 10:55:55.962] [INFO] [MInit._inits.39] Copy gputemp from Data/gputemp to /home/shirish/.i-nex/gputemp
    [01/20/2015 10:55:55.963] [INFO] [Finfosys.Form_Open.231] Settings default dir = /home/shirish/.i-nex
    [01/20/2015 10:55:55.963] [INFO] [Finfosys.Form_Open.232] Check for Battery
    [01/20/2015 10:55:55.963] [INFO] [Finfosys.Form_Open.234] Check for Usb device plugged
    [01/20/2015 10:55:56.081] [INFO] [Finfosys.Form_Open.236] Check for Drives
    [01/20/2015 10:55:56.081] [INFO] [Disk_Drives._inits.71] Add Drives to ComboBox
    [01/20/2015 10:55:56.081] [INFO] [Finfosys.Form_Open.238] Check for Drives..
    [01/20/2015 10:55:56.081] [INFO] [Disk_Drives._init_2.83] Add Drives to ComboBox..
    [01/20/2015 10:55:56.082] [INFO] [Disk_Drives.get_informations.100] Deleting data from variables
    [01/20/2015 10:55:56.082] [INFO] [Disk_Drives.get_informations.102] Get informations of Drives
    [01/20/2015 10:55:56.083] [INFO] [Disk_Drives.get_informations.141] Get informations of Drives Done
    [01/20/2015 10:55:56.11] [INFO] [Finfosys.Form_Open.240] Check for Drives....
    [01/20/2015 10:55:56.11] [INFO] [Disk_Drives.get_informations.100] Deleting data from variables
    [01/20/2015 10:55:56.11] [INFO] [Disk_Drives.get_informations.102] Get informations of Drives
    [01/20/2015 10:55:56.111] [INFO] [Disk_Drives.get_informations.141] Get informations of Drives Done
    [01/20/2015 10:55:56.122] [INFO] [Finfosys.Form_Open.242] Check for Input Drives
    [01/20/2015 10:55:56.123] [INFO] [Input_Devices._inits.30] Add Input Devices to ComboBox..
    [01/20/2015 10:55:56.137] [INFO] [Finfosys.Form_Open.244] Check available network devices
    [01/20/2015 10:55:56.137] [INFO] [Network.inits.26] Add Network Devices to ComboBox
    [01/20/2015 10:55:56.138] [INFO] [Finfosys.Form_Open.246] Check available graphic DSub, DVI etc
    [01/20/2015 10:55:56.138] [INFO] [Finfosys.Form_Open.248] Call to Graphic
    [01/20/2015 10:55:56.186] [INFO] [Finfosys.Form_Open.250] Check sound cards
    [01/20/2015 10:55:56.447] [INFO] [Finfosys.Form_Open.252] Check for default display manager
    [01/20/2015 10:55:56.461] [INFO] [Finfosys.Form_Open.258] Default display manager is Deafult DM: /usr/sbin/gdm3
    [01/20/2015 10:55:56.461] [INFO] [Finfosys.Form_Open.266] Check Dospam uptime
    [01/20/2015 10:55:56.503] [INFO] [Finfosys.Form_Open.268] Check System
     shirish@debian
     OS: Debian 8.0 jessie
     Kernel: x86_64 Linux 3.16.0-4-amd64
     Uptime: 21h 30m
     Packages: 4868
     Shell: inex
     Resolution: 1600x900
     DE: MATE 1.8.1
     WM: Metacity (Marco)
     WM Theme: Not Found
    'Menta' [GTK2]
    , 'Menta' [GTK3]
     Icon Theme: menta
     Font: Sans 12
     CPU: Pentium Dual-Core CPU E5400 @ 2.7GHz
    
     RAM: 896MB / 2000MB
    [01/20/2015 10:55:58.889] [INFO] [Finfosys.Form_Open.270] Call to Distribution_Detect
    [01/20/2015 10:55:58.889] [INFO] [Finfosys.Form_Open.272] Check Bios
    [01/20/2015 10:55:58.89] [INFO] [Finfosys.Form_Open.274] Check Kernels
    [01/20/2015 10:55:58.894] [INFO] [Finfosys.Form_Open.276] Check graphic card
    [01/20/2015 10:55:59.274] [INFO] [Finfosys.Form_Open.279] Set Combobox to cpu0
    [01/20/2015 10:55:59.274] [INFO] [Finfosys.ComboBox1_Click.288] Checking procesors
    [01/20/2015 10:55:59.275] [INFO] [FFlags.ht.99] Not detect HT
    [01/20/2015 10:55:59.275] [INFO] [Finfosys.Wykrywanie_procesorow.667] Get info from database
    [01/20/2015 10:55:59.275] [INFO] [FCpudb._inits.26] Not Use CPU Vendor from ENV
    [01/20/2015 10:55:59.275] [INFO] [FCpudb._inits.79] Use Intel CPU Database
    [01/20/2015 10:55:59.276] [INFO] [FCpudb._inits.83] Decode CPU Database
    [01/20/2015 10:55:59.6] [INFO] [FCpudb._inits.87] Replace CPU Strings to Null
    Pentium E5400
    [01/20/2015 10:56:02.676] [INFO] [FCpudb._inits.141] Current position of processor = Pentium************E5400* is = 729
    [01/20/2015 10:56:02.676] [INFO] [FCpudb._inits.142] Detect CPU As = Pentium E5400
    [01/20/2015 10:56:02.676] [INFO] [FCpudb._inits.143] 
    If Detected CPU is wrong CPU. 
    Please submit report at forum 
    http://forum.i-nex.pl/ 
    
    [01/20/2015 10:56:02.679] [INFO] [Finfosys.Form_Open.283] 7.4.0
    [01/20/2015 10:56:15.627] [INFO] [Finfosys.Form_Close.1151] Good bye!
    gbx3: warning: 4 allocation(s) non freed.
    
As can be seen getting the warning on the last line.

**Comment by eloaders** [comment]
check if the bug has been fixed

**Comment by shirishag75** [comment]
I cannot check as the binary isn't built :( See #28  for more.

**Comment by eloaders** [comment]
fixed?

**Comment by alphastar868** [comment]
I've compiled with the latest **Gambas 3.9.1** (_gambas-code-7923-gambas-trunk.zip_) and I still get this warning.

This should probably be filed upstream as an issue/for clarification on the [Gambas3 Bugtracker](http://gambas.sourceforge.net/en/main.html), as there are similar issues [here](http://gambas.8142.n7.nabble.com/TrayIcon-question-td55955.html) and [here](https://sourceforge.net/p/gambas/mailman/message/32212133/) that were resolved with newer builds.

**Comment by shirishag75** [comment]
filed at https://sourceforge.net/p/gambas/mailman/message/35412430/ . Just needs somebody to prod it a bit if needed. The bug-tracker seems to be closed to outsiders hence put it on the ML.
